[workspace]
members = [
    "pinpam-core",
    "pinpam-pam", 
    "pinutil"
]
resolver = "2"

[workspace.dependencies]
'tss-esapi' = { version = "7.6.0" }
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
rust-i18n = "3.1.5"
